
volumes:
  calibreweb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CALIBREWEB_DATA_PATH}
    name: ${TANGO_APP_NAME}_calibreweb_data
  calibreweb_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CALIBREWEB_MEDIA_PATH}
    name: ${TANGO_APP_NAME}_calibreweb_media

services:
  calibreweb:
    image: ${CALIBREWEB_IMAGE_FIXED_VAR}:${CALIBREWEB_VERSION_FIXED_VAR:-latest}
    container_name: ${TANGO_APP_NAME}_calibreweb
    depends_on: 
      - service_init
    restart: unless-stopped
    container_name: ${TANGO_APP_NAME}_calibreweb
    volumes:
      # will contain calibre-web configuration
      - calibreweb_data:/config
      # different paths used by calibreweb
      - calibreweb_media:/calibreweb_db
    environment:
      - PUID=${TANGO_USER_ID:-0}
      - PGID=${TANGO_GROUP_ID:-0}
      - DOCKER_MODS=studioetrange/calibre-mod:${CALIBRE_MOD_VERSION_FIXED_VAR:-latest}
      - AUTO_CREATE_DB=/calibreweb_db
      - CALIBRE_CONFIG_DIRECTORY=/config/calibre
      - CALIBRE_TEMP_DIR=/config/calibre/tmp
      - CALIBRE_CACHE_DIRECTORY=/config/cache/calibre
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : calibreweb -------------------------
      - "traefik.http.services.calibreweb.loadbalancer.server.port=8083"
      - "traefik.http.services.calibreweb.loadbalancer.server.scheme=http"
      - "traefik.http.services.calibreweb.loadbalancer.passhostheader=true"
      # middlewares : calibreweb
      # service router : calibreweb
      - "traefik.http.routers.calibreweb.entrypoints=${CALIBREWEB_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.calibreweb.rule=HostRegexp(`{subdomain:${CALIBREWEB_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.calibreweb.priority=${CALIBREWEB_PRIORITY}"
      - "traefik.http.routers.calibreweb.service=calibreweb"
      - "traefik.http.routers.calibreweb-secure.entrypoints=${CALIBREWEB_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.calibreweb-secure.rule=HostRegexp(`{subdomain:${CALIBREWEB_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.calibreweb-secure.priority=${CALIBREWEB_PRIORITY}"
      - "traefik.http.routers.calibreweb-secure.service=calibreweb"
      - "traefik.http.routers.calibreweb-secure.tls=true"
      - "traefik.http.routers.calibreweb-secure.tls.domains[0].main=${CALIBREWEB_SUBDOMAIN:-}${TANGO_DOMAIN:-.*}"
      # service router middlewares : calibreweb
      - "traefik.http.routers.calibreweb.middlewares=error-middleware"
      - "traefik.http.routers.calibreweb-secure.middlewares=error-middleware"
    networks:
      - default
    expose:
      - 8083/tcp
