# networks:
#   dcksocketproxy:
#     driver: bridge
#     internal: true
#     name: ${TANGO_CTX_NAME}_dcksocketproxy
networks:
  dcksocketproxy:
    name: ${TANGO_CTX_NETWORK_NAME}_dcksocketproxy

services:
  dcksocketproxy:
    image: ${DCKSOCKETPROXY_IMAGE}:${DCKSOCKETPROXY_VERSION:-latest}
    container_name: ${TANGO_CTX_NAME}_dcksocketproxy
    depends_on:
      - service_init
    restart: unless-stopped
    privileged: true
    environment:
      - LOG_LEVEL=info
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=1
      - DELETE=1
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1
      - VOLUMES=1
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
    networks:
      - dcksocketproxy