services:
  firefox:
    image: ${FIREFOX_IMAGE_FIXED_VAR}:${FIREFOX_VERSION_FIXED_VAR:-latest}
    container_name: ${TANGO_CTX_NAME}_firefox
    depends_on: 
      - service_init
    restart: unless-stopped
    shm_size: 2gb
    environment:
      - USER_ID=${TANGO_USER_ID:-0}
      - GROUP_ID=${TANGO_GROUP_ID:-0}
      - KEEP_APP_RUNNING=1
      - DISPLAY_WIDTH=${FIREFOX_WIDTH:-1280}
      - DISPLAY_HEIGHT=${FIREFOX_HEIGHT:-768}
      - SECURE_CONNECTION=0
      - CLEAN_TMP_DIR=1
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : firefox -------------------------
      - "traefik.http.services.firefox.loadbalancer.server.port=5800"
      - "traefik.http.services.firefox.loadbalancer.server.scheme=http"
      - "traefik.http.services.firefox.loadbalancer.passhostheader=true"
      # middlewares definition : firefox
      # service router : firefox
      - "traefik.http.routers.firefox.entrypoints=${FIREFOX_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.firefox.rule=HostRegexp(`{subdomain:${FIREFOX_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.firefox.priority=${FIREFOX_PRIORITY}"
      - "traefik.http.routers.firefox.service=firefox"
      - "traefik.http.routers.firefox-secure.entrypoints=${FIREFOX_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.firefox-secure.rule=HostRegexp(`{subdomain:${FIREFOX_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.firefox-secure.priority=${FIREFOX_PRIORITY}"
      - "traefik.http.routers.firefox-secure.service=firefox"
      - "traefik.http.routers.firefox-secure.tls=true"
      - "traefik.http.routers.firefox-secure.tls.domains[0].main=${FIREFOX_SUBDOMAIN:-}${TANGO_DOMAIN:-.*}"
      # service router middlewares : firefox
      - "traefik.http.routers.firefox.middlewares=error-middleware"
      - "traefik.http.routers.firefox-secure.middlewares=error-middleware"
      # --------------------------------------------------
    networks:
      - default
    expose:
      - 5800/tcp
      # VNC port
      - 5900