volumes:
  kcc_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${KCC_DATA_PATH}
    name: ${TANGO_CTX_NAME}_kcc_data

services:
  kcc:
    image: ${KCC_DOCKER_IMAGE_FIXED_VAR}:${KCC_DOCKER_VERSION_FIXED_VAR}
    container_name: ${TANGO_CTX_NAME}_kcc
    depends_on:
      - service_init
    restart: unless-stopped
    volumes:
      # will contain kcc configuration
      - kcc_data:/config
    environment:
      - PUID=${TANGO_USER_ID:-0}
      - PGID=${TANGO_GROUP_ID:-0}
      - KCC_VERSION=${KCC_GIT_VERSION_FIXED_VAR}
      - REPO_GIT=${KCC_REPO_GIT_FIXED_VAR}
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : kcc -------------------------
      - "traefik.http.services.kcc.loadbalancer.server.port=8080"
      - "traefik.http.services.kcc.loadbalancer.server.scheme=http"
      - "traefik.http.services.kcc.loadbalancer.passhostheader=true"
      # middlewares definition : kcc
      # service router : kcc
      - "traefik.http.routers.kcc.entrypoints=${KCC_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.kcc.rule=HostRegexp(`{subdomain:${KCC_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.kcc.priority=${KCC_PRIORITY}"
      - "traefik.http.routers.kcc.service=kcc"
      - "traefik.http.routers.kcc-secure.entrypoints=${KCC_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.kcc-secure.rule=HostRegexp(`{subdomain:${KCC_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.kcc-secure.priority=${KCC_PRIORITY}"
      - "traefik.http.routers.kcc-secure.service=kcc"
      - "traefik.http.routers.kcc-secure.tls=true"
      - "traefik.http.routers.kcc-secure.tls.domains[0].main=${KCC_SUBDOMAIN:-}${TANGO_DOMAIN:-.*}"
      # service router middlewares : kcc
      - "traefik.http.routers.kcc.middlewares=error-middleware"
      - "traefik.http.routers.kcc-secure.middlewares=error-middleware"
      # --------------------------------------------------
    networks:
      - default
    expose:
      - 8080/tcp
