volumes:
  mkvtoolnix_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MKVTOOLNIX_DATA_PATH}
    name: ${TANGO_CTX_NAME}_mkvtoolnix_data
  
services:
  mkvtoolnix:
    image: ${MKVTOOLNIX_IMAGE}:${MKVTOOLNIX_VERSION:-latest}
    container_name: ${TANGO_CTX_NAME}_mkvtoolnix
    depends_on:
      - service_init
    restart: unless-stopped
    volumes:
      # will contain mkvtoolnix configuration
      - mkvtoolnix_data:/config
    environment:
      - USER_ID=${TANGO_USER_ID:-0}
      - GROUP_ID=${TANGO_GROUP_ID:-0}
      - KEEP_APP_RUNNING=1
      - DISPLAY_WIDTH=${MKVTOOLNIX_WIDTH:-1280}
      - DISPLAY_HEIGHT=${MKVTOOLNIX_HEIGHT-:768}
      - SECURE_CONNECTION=0
      - CLEAN_TMP_DIR=1
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : mkvtoolnix -------------------------
      - "traefik.http.services.mkvtoolnix.loadbalancer.server.port=5800"
      - "traefik.http.services.mkvtoolnix.loadbalancer.server.scheme=http"
      - "traefik.http.services.mkvtoolnix.loadbalancer.passhostheader=true"
      # middlewares definition : mkvtoolnix
      # service router : mkvtoolnix
      - "traefik.http.routers.mkvtoolnix.entrypoints=${MKVTOOLNIX_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.mkvtoolnix.rule=HostRegexp(`{subdomain:${MKVTOOLNIX_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.mkvtoolnix.priority=${MKVTOOLNIX_PRIORITY}"
      - "traefik.http.routers.mkvtoolnix.service=mkvtoolnix"
      - "traefik.http.routers.mkvtoolnix-secure.entrypoints=${MKVTOOLNIX_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.mkvtoolnix-secure.rule=HostRegexp(`{subdomain:${MKVTOOLNIX_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.mkvtoolnix-secure.priority=${MKVTOOLNIX_PRIORITY}"
      - "traefik.http.routers.mkvtoolnix-secure.service=mkvtoolnix"
      - "traefik.http.routers.mkvtoolnix-secure.tls=true"
      - "traefik.http.routers.mkvtoolnix-secure.tls.domains[0].main=${MKVTOOLNIX_SUBDOMAIN:-}${TANGO_DOMAIN:-.*}"
      # service router middlewares : mkvtoolnix
      - "traefik.http.routers.mkvtoolnix.middlewares=error-middleware"
      - "traefik.http.routers.mkvtoolnix-secure.middlewares=error-middleware"
      # --------------------------------------------------
    networks:
      - default
    expose:
      - 5800/tcp