volumes:
  romvault_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROMVAULT_DATA_PATH}
    name: ${TANGO_CTX_NAME}_romvault_data
  
services:
  romvault:
    image: ${ROMVAULT_IMAGE}:${ROMVAULT_VERSION:-latest}
    container_name: ${TANGO_CTX_NAME}_romvault
    depends_on:
      - service_init
    restart: unless-stopped
    volumes:
      - romvault_data:/config
      - download:/download
    environment:
      - USER_ID=${TANGO_USER_ID:-0}
      - GROUP_ID=${TANGO_GROUP_ID:-0}
      - KEEP_APP_RUNNING=1
      - DISPLAY_WIDTH=${ROMVAULT_WIDTH:-1280}
      - DISPLAY_HEIGHT=${ROMVAULT_HEIGHT-:768}
      - SECURE_CONNECTION=0
      - CLEAN_TMP_DIR=1
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : romvault -------------------------
      - "traefik.http.services.romvault.loadbalancer.server.port=5800"
      - "traefik.http.services.romvault.loadbalancer.server.scheme=http"
      - "traefik.http.services.romvault.loadbalancer.passhostheader=true"
      # middlewares definition : romvault
      # service router : romvault
      - "traefik.http.routers.romvault.entrypoints=${ROMVAULT_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.romvault.rule=Host(`${ROMVAULT_SUBDOMAIN:-}${TANGO_DOMAIN:-}`)"
      - "traefik.http.routers.romvault.priority=${ROMVAULT_PRIORITY}"
      - "traefik.http.routers.romvault.service=romvault"
      - "traefik.http.routers.romvault-secure.entrypoints=${ROMVAULT_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.romvault-secure.rule=Host(`${ROMVAULT_SUBDOMAIN:-}${TANGO_DOMAIN:-}`)"
      - "traefik.http.routers.romvault-secure.priority=${ROMVAULT_PRIORITY}"
      - "traefik.http.routers.romvault-secure.service=romvault"
      - "traefik.http.routers.romvault-secure.tls=true"
      - "traefik.http.routers.romvault-secure.tls.domains[0].main=${ROMVAULT_SUBDOMAIN:-}${TANGO_DOMAIN:-}"
      # service router middlewares : romvault
      - "traefik.http.routers.romvault.middlewares=error-middleware"
      - "traefik.http.routers.romvault-secure.middlewares=error-middleware"
      # --------------------------------------------------
    networks:
      - default
    expose:
      # service template
      - 5800/tcp
      # other non used port : VNC
      - 5900
    build:
      context: https://github.com/StudioEtrange/docker-romvault.git#main