volumes:
  uptimekuma_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${UPTIMEKUMA_DATA_PATH}
    name: ${TANGO_CTX_NAME}_uptimekuma_data

services:
  uptimekuma:
    image: ${UPTIMEKUMA_IMAGE_FIXED_VAR}:${UPTIMEKUMA_VERSION_FIXED_VAR:-latest}
    container_name: ${TANGO_CTX_NAME}_uptimekuma
    depends_on: 
      - service_init
    restart: unless-stopped
    volumes:
      - uptimekuma_data:/app/data
    environment:
      - USER_ID=${TANGO_USER_ID:-0}
      - GROUP_ID=${TANGO_GROUP_ID:-0}
      - DISPLAY_WIDTH=${UPTIMEKUMA_WIDTH:-1280}
      - DISPLAY_HEIGHT=${UPTIMEKUMA_HEIGHT:-768}
      - PUID=${TANGO_USER_ID:-0}
      - PGID=${TANGO_GROUP_ID:-0}
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : uptimekuma -------------------------
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
      - "traefik.http.services.uptimekuma.loadbalancer.server.scheme=http"
      - "traefik.http.services.uptimekuma.loadbalancer.passhostheader=true"
      # middlewares definition : uptimekuma
      # service router : uptimekuma
      - "traefik.http.routers.uptimekuma.entrypoints=${UPTIMEKUMA_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.uptimekuma.rule=HostRegexp(`{subdomain:${UPTIMEKUMA_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.uptimekuma.priority=${UPTIMEKUMA_PRIORITY}"
      - "traefik.http.routers.uptimekuma.service=uptimekuma"
      - "traefik.http.routers.uptimekuma-secure.entrypoints=${UPTIMEKUMA_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.uptimekuma-secure.rule=HostRegexp(`{subdomain:${UPTIMEKUMA_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.uptimekuma-secure.priority=${UPTIMEKUMA_PRIORITY}"
      - "traefik.http.routers.uptimekuma-secure.service=uptimekuma"
      - "traefik.http.routers.uptimekuma-secure.tls=true"
      - "traefik.http.routers.uptimekuma-secure.tls.domains[0].main=${UPTIMEKUMA_SUBDOMAIN:-}${TANGO_DOMAIN:-.*}"
      # service router middlewares : uptimekuma
      - "traefik.http.routers.uptimekuma.middlewares=error-middleware"
      - "traefik.http.routers.uptimekuma-secure.middlewares=error-middleware"
      # --------------------------------------------------
    networks:
      - default
    expose:
      # service uptimekuma
      - 3001/tcp
