volumes:
  xbackbone_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${XBACKBONE_DATA_PATH}
    name: ${TANGO_CTX_NAME}_xbackbone_data

services:
  xbackbone:
    image: ${XBACKBONE_IMAGE}:${XBACKBONE_VERSION:-latest}
    container_name: ${TANGO_CTX_NAME}_xbackbone
    depends_on: 
      - service_init
    restart: unless-stopped
    volumes:
      - xbackbone_data:/config
    environment:
      - PUID=${TANGO_USER_ID:-0}
      - PGID=${TANGO_GROUP_ID:-0}
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      # service : xbackbone -------------------------
      - "traefik.http.services.xbackbone.loadbalancer.server.port=80"
      - "traefik.http.services.xbackbone.loadbalancer.server.scheme=http"
      - "traefik.http.services.xbackbone.loadbalancer.passhostheader=true"
      # middlewares definition : xbackbone
      # service router : xbackbone
      - "traefik.http.routers.xbackbone.entrypoints=${XBACKBONE_ENTRYPOINTS:-entry_main_http}"
      - "traefik.http.routers.xbackbone.rule=HostRegexp(`{subdomain:${XBACKBONE_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.xbackbone.priority=${XBACKBONE_PRIORITY}"
      - "traefik.http.routers.xbackbone.service=xbackbone"
      - "traefik.http.routers.xbackbone-secure.entrypoints=${XBACKBONE_ENTRYPOINTS_SECURE:-entry_main_http_secure}"
      - "traefik.http.routers.xbackbone-secure.rule=HostRegexp(`{subdomain:${XBACKBONE_SUBDOMAIN:-}}{domain:${TANGO_DOMAIN:-.*}}`)"
      - "traefik.http.routers.xbackbone-secure.priority=${XBACKBONE_PRIORITY}"
      - "traefik.http.routers.xbackbone-secure.service=xbackbone"
      - "traefik.http.routers.xbackbone-secure.tls=true"
      - "traefik.http.routers.xbackbone-secure.tls.domains[0].main=${XBACKBONE_SUBDOMAIN:-}${TANGO_DOMAIN:-.*}"
      # service router middlewares : xbackbone
      - "traefik.http.routers.xbackbone.middlewares=error-middleware"
      - "traefik.http.routers.xbackbone-secure.middlewares=error-middleware"
      # --------------------------------------------------
    networks:
      - default
    expose:
      - 80/tcp