#!/usr/bin/env bash


# NOTE : will set remote transmission port


# NEED transmission volumes
# NEED lib pia port forward
# WAIT for vpn and transmission service up

# load tango libs
for f in /pool/tango/libs/*; do
	[ -f "${f}" ] && . ${f}
done

# load app libs
[ ! "${TANGO_NOT_IN_APP}" = "1" ] && for f in /pool/${TANGO_APP_NAME}/scripts/*.sh; do [ -f "${f}" ] && . ${f}; done


PLUGIN="transmission_pia_port"

echo "* Plugin : ${PLUGIN}"

echo "L-- STEP : install plugin"
echo "  -"
echo "L-- STEP : setup plugin"
echo "  -"
echo "L-- STEP : run plugin"

# ask PIA vpn provider to forward a port
pia_get_port

# set transmission with this port
transmission_set_port "$?"