#!/bin/bash
_CURRENT_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
_CURRENT_RUNNING_DIR="$( cd "$( dirname "." )" && pwd )"

TANGO_ROOT="${_CURRENT_FILE_DIR}"

STELLA_LOG_STATE="OFF"
. "${TANGO_ROOT}/stella-link.sh" include

. "${TANGO_ROOT}/src/tango-init.sh" $@

. "${TANGO_ROOT}/src/tango-set-arg.sh" $@

. "${TANGO_ROOT}/src/tango-parse-arg.sh" $@

. "${TANGO_ROOT}/src/tango-prepare-action.sh" $@

. "${TANGO_ROOT}/src/tango-before-action.sh" $@

. "${TANGO_ROOT}/src/tango-action.sh" $@

. "${TANGO_ROOT}/src/tango-after-action.sh" $@