
volumes:
  website_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/${WEBROOT}
    name: ${TANGO_APP_NAME}_website_data

services:
  
  website:
    image: httpd:${WEBSITE_VERSION:-latest}
    container_name: ${TANGO_APP_NAME}_website
    depends_on: 
      - service_init
    restart: unless-stopped
    volumes:
      - website_data:/usr/local/apache2/htdocs
    labels:
      - "${TANGO_INSTANCE_NAME}.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.website.entrypoints=${WEBSITE_ENTRYPOINTS:-web_main}"
      - "traefik.http.routers.website.rule=HostRegexp(`{subdomain:website}.{domain:${TANGO_DOMAIN:-.*}}`) && PathPrefix(`/web`)"
      - "traefik.http.routers.website.priority=${WEBSITE_REDIRECT_HTTPS_PRIORITY:-200}"
      - "traefik.http.routers.website.service=website"

      - "traefik.http.routers.website-secure.entrypoints=${WEBSITE_ENTRYPOINTS_SECURE:-web_main_secure}"
      - "traefik.http.routers.website-secure.rule=HostRegexp(`{subdomain:website}.{domain:${TANGO_DOMAIN:-.*}}`) && PathPrefix(`/web`)"
      - "traefik.http.routers.website-secure.service=website"
      - "traefik.http.routers.website-secure.tls=true"
      - "traefik.http.routers.website-secure.tls.domains[0].main=website.${TANGO_DOMAIN:-.*}"

      - "traefik.http.services.website.loadbalancer.server.port=80"
      - "traefik.http.services.website.loadbalancer.server.scheme=http"
      - "traefik.http.services.website.loadbalancer.passhostheader=true"

      - "traefik.http.middlewares.website-stripprefix.stripprefix.prefixes=/web, /web/"

      - "traefik.http.routers.website.middlewares=website-stripprefix"
      - "traefik.http.routers.website-secure.middlewares=website-stripprefix"
    networks:
      - default
    expose:
      - 80