#!/usr/bin/env bash


echo "---------==---- $TANGO_APP_NAME_CAPS init ----==---------"
echo Init of ${TANGO_APP_NAME}
echo L-- create [$APP_DATA_PATH/$WEBROOT] {/data/$WEBROOT}
mkdir -p "/data/$WEBROOT"